name: Build and Test

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: build-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run type checker
        run: npm run type-check
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run build
